/**
 * SPICE netlist exporter.
 *
 * Generates a Berkeley SPICE 3 / ngspice / LTspice compatible .cir file
 * from the breadboard component list.
 *
 * Element syntax reference:
 *   R  — R<id> <n+> <n-> <ohms>
 *   C  — C<id> <n+> <n-> <farads>  [IC=<v>]
 *   L  — L<id> <n+> <n-> <henries>
 *   V  — V<id> <n+> <n-> DC <volts>
 *   I  — I<id> <n+> <n-> DC <amps>
 *   D  — D<id> <anode> <cathode> <model>
 *   Q  — Q<id> <collector> <base> <emitter> <model>
 *   M  — M<id> <drain> <gate> <source> <bulk> <model>
 *   X  — X<id> <pins...> <subckt>  (opamp, MCU)
 */

// ── Node name sanitiser ───────────────────────────────────────────────────────
const GROUND_NODES = new Set(['0', 'GND', 'PWR_L_NEG', 'PWR_R_NEG'])
const VCC_NODES    = new Set(['PWR_L_POS', 'PWR_R_POS'])

function spiceNode(node) {
  if (!node || GROUND_NODES.has(node)) return '0'
  if (VCC_NODES.has(node))             return 'VCC'
  // Sanitise: SPICE node names must start with a letter or digit
  return node.replace(/[^a-zA-Z0-9]/g, '_')
}

// ── Engineering notation formatter ───────────────────────────────────────────
function eng(v) {
  const a = Math.abs(v)
  if (a === 0)          return '0'
  if (a >= 1e9)         return `${(v/1e9).toPrecision(4)}G`
  if (a >= 1e6)         return `${(v/1e6).toPrecision(4)}Meg`
  if (a >= 1e3)         return `${(v/1e3).toPrecision(4)}k`
  if (a >= 1)           return `${v.toPrecision(4)}`
  if (a >= 1e-3)        return `${(v/1e-3).toPrecision(4)}m`
  if (a >= 1e-6)        return `${(v/1e-6).toPrecision(4)}u`
  if (a >= 1e-9)        return `${(v/1e-9).toPrecision(4)}n`
  if (a >= 1e-12)       return `${(v/1e-12).toPrecision(4)}p`
  return v.toExponential(3)
}

/**
 * Generate a SPICE netlist string from the board state.
 *
 * @param {Array}  components  — from store
 * @param {Array}  wires       — from store (used for title comment)
 * @param {Object} simResult   — optional, used for initial conditions
 * @param {string} title       — circuit title
 */
export function generateSpice(components, wires = [], simResult = null, title = 'Breadboard Export') {
  const lines   = []
  const models  = {}        // modelName → .model line
  const subcktDefs = {}    // any subcircuit definitions needed

  // ── Header ────────────────────────────────────────────────────────────────
  lines.push(`* ${title}`)
  lines.push(`* Generated by Breadboard Simulator`)
  lines.push(`* ${new Date().toISOString()}`)
  lines.push(`* ${components.length} components, ${wires.length} wires`)
  lines.push('')
  lines.push('.title ' + title)
  lines.push('')

  // ── Component elements ────────────────────────────────────────────────────
  let lineCount = 0
  for (const comp of components) {
    const p  = comp.params || {}
    const n  = comp.nodes  || {}
    const id = comp.id.replace(/[^a-zA-Z0-9]/g, '')  // SPICE IDs alphanumeric

    let element = null

    switch (comp.type) {

      // ── Voltage source ───────────────────────────────────────────────────
      case 'battery':
        element = `V${id} ${spiceNode(n.pos)} ${spiceNode(n.neg)} DC ${eng(p.voltage ?? 9)}`
        break

      // ── Passive ──────────────────────────────────────────────────────────
      case 'resistor':
        element = `R${id} ${spiceNode(n.p)} ${spiceNode(n.n)} ${eng(p.resistance ?? 1000)}`
        break

      case 'capacitor': {
        const ic = simResult?.node_voltages
          ? (simResult.node_voltages[n.p] ?? 0) - (simResult.node_voltages[n.n] ?? 0)
          : 0
        element = `C${id} ${spiceNode(n.p)} ${spiceNode(n.n)} ${eng(p.capacitance ?? 1e-6)}` +
                  (Math.abs(ic) > 0.001 ? ` IC=${ic.toFixed(4)}` : '')
        break
      }

      case 'potentiometer': {
        const R   = p.resistance ?? 10000
        const pos = Math.max(0.001, Math.min(0.999, p.pos ?? 0.5))
        lines.push(`R${id}A ${spiceNode(n.a)} ${spiceNode(n.wiper)} ${eng(R * pos)}`)
        lines.push(`R${id}B ${spiceNode(n.wiper)} ${spiceNode(n.b)} ${eng(R * (1-pos))}`)
        lineCount += 2
        continue
      }

      // ── Diodes ───────────────────────────────────────────────────────────
      case 'diode':
        element = `D${id} ${spiceNode(n.anode)} ${spiceNode(n.cathode)} D_1N4148`
        models['D_1N4148'] = '.model D_1N4148 D(IS=2.52e-9 N=1.752 RS=0.568 CJO=4p TT=20n)'
        break

      case 'led': {
        const color   = p.color   || 'red'
        const vf      = p.vf      || 2.0
        const mName   = `D_LED_${color.toUpperCase()}`
        // Approximate LED SPICE model: adjust EG to shift Vf
        const eg      = Math.max(0.5, vf * 0.85)
        element = `D${id} ${spiceNode(n.anode)} ${spiceNode(n.cathode)} ${mName}`
        models[mName] = `.model ${mName} D(IS=1.6e-19 N=2.0 RS=5 EG=${eg.toFixed(2)} XTI=3)`
        break
      }

      case 'zener': {
        const mName = `DZ_${id}`
        element = `D${id} ${spiceNode(n.anode)} ${spiceNode(n.cathode)} ${mName}`
        models[mName] = `.model ${mName} D(IS=1e-12 N=1.0 RS=2 BV=${eng(p.vz ?? 5.1)} IBV=1m)`
        break
      }

      // ── BJT ──────────────────────────────────────────────────────────────
      case 'bjt': {
        const bjtType = (p.bjt_type || 'NPN').toUpperCase()
        const mName   = `Q_${id}`
        element = `Q${id} ${spiceNode(n.collector)} ${spiceNode(n.base)} ${spiceNode(n.emitter)} ${mName}`
        models[mName] = `.model ${mName} ${bjtType}(IS=1e-14 BF=${p.hfe ?? 100} BR=${Math.max(1, (p.hfe ?? 100)/10)} VAF=200 IKF=0.3 ISE=1e-11 NE=1.5 NF=1 NR=1)`
        break
      }

      // ── MOSFET ───────────────────────────────────────────────────────────
      case 'mosfet': {
        const chanType = (p.mtype || 'N').toUpperCase() === 'P' ? 'PMOS' : 'NMOS'
        const mName    = `M_${id}`
        // SPICE Level-1 Shichman-Hodges params
        // KP = 2*K (SPICE uses W/L=1 by default)
        element = `M${id} ${spiceNode(n.drain)} ${spiceNode(n.gate)} ${spiceNode(n.source)} ${spiceNode(n.source)} ${mName} W=100u L=10u`
        models[mName] = `.model ${mName} ${chanType}(VTO=${eng(p.vth ?? 2.0)} KP=${eng((p.K ?? 0.01)*2)} LAMBDA=${eng(p.lam ?? 0.01)} GAMMA=0 PHI=0.6)`
        break
      }

      // ── Op-Amp (subcircuit) ───────────────────────────────────────────────
      case 'opamp': {
        const mName = `XOPAMP_${id}`
        element = `X${id} ${spiceNode(n.non_inv)} ${spiceNode(n.inv)} ${spiceNode(n.v_pos)} ${spiceNode(n.v_neg)} ${spiceNode(n.out)} IDEAL_OPAMP`
        if (!subcktDefs['IDEAL_OPAMP']) {
          subcktDefs['IDEAL_OPAMP'] = [
            '.subckt IDEAL_OPAMP INP INN VCC VEE OUT',
            `* Ideal op-amp: Aol=${eng(p.Aol ?? 1e5)}, Rin=${eng(p.Rin ?? 1e6)}, Rout=${eng(p.Rout ?? 75)}`,
            `RIN  INP INN ${eng(p.Rin ?? 1e6)}`,
            `EOUT _OUT1 VEE VALUE={LIMIT(${eng(p.Aol ?? 1e5)}*V(INP,INN), 0, V(VCC,VEE))}`,
            `ROUT _OUT1 OUT ${eng(p.Rout ?? 75)}`,
            '.ends IDEAL_OPAMP',
          ].join('\n')
        }
        break
      }

      // ── Current source ───────────────────────────────────────────────────
      case 'current_source':
        element = `I${id} ${spiceNode(n.pos)} ${spiceNode(n.neg)} DC ${eng(p.current ?? 0.001)}`
        break

      default:
        lines.push(`* Skipped ${id} (type '${comp.type}' not supported in SPICE export)`)
        continue
    }

    if (element) {
      lines.push(element)
      lineCount++
    }
  }

  // ── Subcircuit definitions ────────────────────────────────────────────────
  if (Object.keys(subcktDefs).length > 0) {
    lines.push('')
    lines.push('* ── Subcircuit definitions ─────────────────────────────────')
    Object.values(subcktDefs).forEach(def => { lines.push(def); lines.push('') })
  }

  // ── .model statements ────────────────────────────────────────────────────
  if (Object.keys(models).length > 0) {
    lines.push('')
    lines.push('* ── Device models ──────────────────────────────────────────')
    Object.values(models).forEach(m => lines.push(m))
  }

  // ── Analysis commands ────────────────────────────────────────────────────
  lines.push('')
  lines.push('* ── Analysis ───────────────────────────────────────────────')
  lines.push('.op')
  lines.push('* Uncomment for transient:')
  lines.push('* .tran 1u 1m')
  lines.push('* Uncomment for AC sweep:')
  lines.push('* .ac dec 100 1Hz 1Meg')
  lines.push('')
  lines.push('.end')

  return lines.join('\n')
}

/**
 * Trigger a browser download of the SPICE netlist.
 */
export function downloadSpice(spiceText, filename = 'circuit.cir') {
  const blob = new Blob([spiceText], { type: 'text/plain' })
  const url  = URL.createObjectURL(blob)
  const a    = document.createElement('a')
  a.href     = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}
